apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: harshil9199-poi-map-app-dev
  annotations:
    argocd/app-name: harshil9199-poi-map-app-dev
    backstage.io/kubernetes-id: harshil9199-poi-map-app
    backstage.io/kubernetes-namespace: harshil9199
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh-deploy/harshil9199-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.a1jxqhzp.eastus2.aroapp.io/dev-pipelines/ns/harshil9199/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.a1jxqhzp.eastus2.aroapp.io/k8s/ns/harshil9199/deployments/harshil9199-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.a1jxqhzp.eastus2.aroapp.io/#https://github.com/rhdh-deploy/harshil9199-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://harshil9199-poi-map-app-harshil9199.apps.a1jxqhzp.eastus2.aroapp.io
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/harshil9199"
  system: workshop-system-harshil9199
  consumesApis:
    - gateway-api-harshil9199
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-harshil9199
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/harshil9199"
